In [23]:
import pandas as pd
import numpy as np

In [24]:
df = pd.read_csv('transaction-logs-1.csv', delimiter=';', dtype=str)
df2 = pd.read_csv('transaction-logs-2.csv', delimiter=';', dtype=str)
df = pd.concat([df, df2], ignore_index=True)
df = df[['Date created', 'Offer SKU', 'Type', 'Quantity', 'Amount']]
df['Offer SKU'] = df['Offer SKU'].replace(['0004925700', '0004928100', '0004928200', '0004928800', '0004555700', '0004933600'], ['0005346800', '0005347000', '0005346900', '0005347100', '0005310300', '0005347200'])

df = df[(df['Type'] == 'Order amount') | (df['Type'] == 'Order amount refund')]
df.to_csv('Transactions.csv', index=False)
df

                 Date created   Offer SKU          Type Quantity  Amount
0       01/01/2024 - 00:37:56  0004934200  Order amount        1   35.54
4       01/01/2024 - 01:54:41  0004934400  Order amount        1   35.54
8       01/01/2024 - 06:43:17  0004928000  Order amount        1   56.24
12      01/01/2024 - 07:48:42  0004475000  Order amount        1   53.99
16      01/01/2024 - 07:58:45  0004473500  Order amount        1   49.49
...                       ...         ...           ...      ...     ...
540579  07/05/2026 - 17:01:33  0004934400  Order amount        1   34.99
540583  07/05/2026 - 17:01:33  0004933900  Order amount        1   34.99
540587  07/05/2026 - 17:30:31  0005213905  Order amount        1  129.99
540591  07/05/2026 - 17:31:23  0000851400  Order amount        1   19.99
540595  07/05/2026 - 17:31:23  0005169800  Order amount        1   34.99

[134442 rows x 5 columns]

In [25]:
temp = df['Date created'].str.split(' - ', expand=True)
df['Date'] = pd.to_datetime(temp[0], format='%d/%m/%Y')

In [26]:
style = pd.read_csv('Style Listing Stock.csv', dtype=str, skiprows=2)
style = style[~style['Style'].isna()]
style = style[style['Style'] != 'Style']
style = style[~style['Category'].isna()]
style = style[['Style', 'Category', 'Department']]
style.head(2)

   Style Category   Department
0    007   GLOVES       LADIES
13  010B     HATS  LEATHER CAP

In [27]:
fe = pd.read_csv('Fashione-EAN 07-05-2026.csv', dtype=str)
fe['Offer SKU'] = fe['PLU']
fe = pd.merge(fe, style, on='Style', how='left')
fe = fe[['Offer SKU', 'Style', 'Colour', 'Size', 'Category']]
fe['Category'] = fe['Category'].fillna('OTHER')
fe.head()

    Offer SKU Style      Colour Size Category
0  0002875800   007    BLK/BLUE    S   GLOVES
1  0002875801   007    BLK/BLUE    M   GLOVES
2  0002875802   007    BLK/BLUE    L   GLOVES
3  0002875803   007    BLK/BLUE   XL   GLOVES
4  0002876200   007  BLK/PURPLE    S   GLOVES

In [28]:
df = df[['Offer SKU', 'Type', 'Quantity', 'Amount']]
df = pd.merge(df, fe, on='Offer SKU', how='left')

In [29]:
df

,Offer SKU,Type,Quantity,Amount,Style,Colour,Size,Category
0,0004934200,Order amount,1,35.54,63753,MANDARIN,ONE SIZE,HANDBAGS
1,0004934400,Order amount,1,35.54,63753,parafin,ONE SIZE,HANDBAGS
2,0004928000,Order amount,1,56.24,62879,light wine,NaN,HANDBAGS
3,0004475000,Order amount,1,53.99,63789,BLACK,ONE SIZE,HANDBAGS
4,0004473500,Order amount,1,49.49,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
134437,0004934400,Order amount,1,34.99,63753,parafin,ONE SIZE,HANDBAGS
134438,0004933900,Order amount,1,34.99,63753,BLACK,ONE SIZE,HANDBAGS
134439,0005213905,Order amount,1,129.99,AWL-1282,BLACK,16,LADIES JACKETS
134440,0000851400,Order amount,1,19.99,TAB,BLACK,NaN,HANDBAGS
134441,0005169800,Order amount,1,34.99,64397,BLACK,ONE SIZE,HANDBAGS