In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('transaction-logs-1.csv', delimiter=';', dtype=str)
df2 = pd.read_csv('transaction-logs-2.csv', delimiter=';', dtype=str)
df = pd.concat([df, df2], ignore_index=True)
df = df[['Date created', 'Offer SKU', 'Type', 'Quantity', 'Amount']]
df['Offer SKU'] = df['Offer SKU'].replace(['0004925700', '0004928100', '0004928200', '0004928800', '0004555700', '0004933600'], ['0005346800', '0005347000', '0005346900', '0005347100', '0005310300', '0005347200'])
df.to_csv('Transactions.csv', index=False)
df

                 Date created   Offer SKU              Type Quantity  Amount
0       01/01/2024 - 00:37:56  0004934200      Order amount        1   35.54
1       01/01/2024 - 00:37:56  0004934200  Shipping charges        1    0.00
2       01/01/2024 - 00:37:56  0004934200        Commission        1   -7.11
3       01/01/2024 - 00:37:56  0004934200    Commission tax        1   -1.42
4       01/01/2024 - 01:54:41  0004934400      Order amount        1   35.54
...                       ...         ...               ...      ...     ...
515146  10/03/2026 - 23:14:35  0004928500    Commission tax        1   -2.00
515147  10/03/2026 - 23:16:16  0005190105      Order amount        1   84.99
515148  10/03/2026 - 23:16:16  0005190105  Shipping charges        1    0.00
515149  10/03/2026 - 23:16:16  0005190105        Commission        1  -17.00
515150  10/03/2026 - 23:16:16  0005190105    Commission tax        1   -3.40

[515151 rows x 5 columns]

In [ ]:
temp = df['Date created'].str.split(' - ', expand=True)
df['Date'] = pd.to_datetime(temp[0], format='%d/%m/%Y')

,Date created,Date received,Transaction Date,Shop,Order number,Invoice number,Transaction Number,Quantity,Category Label,Offer SKU,...,Balance,Currency,Customer order reference,Shop order reference,Billing cycle date,Shop ID,Order line ID,Refund ID,Sales channel,Date
0,01/01/2024 - 00:37:56,19/01/2024 - 04:22:00,NaN,Ashwood Leather,DUX025074121-A,000000245981,NaN,1,Womens Bags & Purses,0004934200,...,110823.20,GBP,NaN,NaN,27/01/2024 - 00:48:35,2472,DUX025074121-A-1,NaN,NaN,2024-01-01
1,01/01/2024 - 00:37:56,19/01/2024 - 04:22:00,NaN,Ashwood Leather,DUX025074121-A,000000245981,NaN,1,Womens Bags & Purses,0004934200,...,110823.20,GBP,NaN,NaN,27/01/2024 - 00:48:35,2472,DUX025074121-A-1,NaN,NaN,2024-01-01
2,01/01/2024 - 00:37:56,19/01/2024 - 04:22:00,NaN,Ashwood Leather,DUX025074121-A,000000245981,NaN,1,Womens Bags & Purses,0004934200,...,110816.09,GBP,NaN,NaN,27/01/2024 - 00:48:35,2472,DUX025074121-A-1,NaN,NaN,2024-01-01
3,01/01/2024 - 00:37:56,19/01/2024 - 04:22:00,NaN,Ashwood Leather,DUX025074121-A,000000245981,NaN,1,Womens Bags & Purses,0004934200,...,110814.67,GBP,NaN,NaN,27/01/2024 - 00:48:35,2472,DUX025074121-A-1,NaN,NaN,2024-01-01
4,01/01/2024 - 01:54:41,NaN,NaN,Ashwood Leather,DUX025074868-A,000000245981,NaN,1,Womens Bags & Purses,0004934400,...,110850.21,GBP,NaN,NaN,27/01/2024 - 00:48:35,2472,DUX025074868-A-1,NaN,NaN,2024-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494105,05/02/2026 - 12:42:00,NaN,NaN,Ashwood Leather,DUX051502105-A,NaN,NaN,1,Womens Bags & Purses,0004930900,...,312707.14,GBP,NaN,NaN,NaN,2472,DUX051502105-A-1,NaN,Initial Channel,2026-02-05
494106,05/02/2026 - 12:49:39,NaN,NaN,Ashwood Leather,DUX051502331-A,NaN,NaN,1,Womens Bags & Purses,0005433500,...,312745.13,GBP,NaN,NaN,NaN,2472,DUX051502331-A-1,NaN,Initial Channel,2026-02-05
494107,05/02/2026 - 12:49:39,NaN,NaN,Ashwood Leather,DUX051502331-A,NaN,NaN,1,Womens Bags & Purses,0005433500,...,312745.13,GBP,NaN,NaN,NaN,2472,DUX051502331-A-1,NaN,Initial Channel,2026-02-05
494108,05/02/2026 - 12:49:39,NaN,NaN,Ashwood Leather,DUX051502331-A,NaN,NaN,1,Womens Bags & Purses,0005433500,...,312737.53,GBP,NaN,NaN,NaN,2472,DUX051502331-A-1,NaN,Initial Channel,2026-02-05
494109,05/02/2026 - 12:49:39,NaN,NaN,Ashwood Leather,DUX051502331-A,NaN,NaN,1,Womens Bags & Purses,0005433500,...,312736.01,GBP,NaN,NaN,NaN,2472,DUX051502331-A-1,NaN,Initial Channel,2026-02-05

In [22]:
style = pd.read_csv('Style Listing Stock.csv', dtype=str, skiprows=2)
style = style[~style['Style'].isna()]
style = style[style['Style'] != 'Style']
style = style[~style['Category'].isna()]
style = style[['Style', 'Category', 'Department']]
style.head(2)

   Style Category   Department
0    007   GLOVES       LADIES
16  010B     HATS  LEATHER CAP

In [23]:
fe = pd.read_csv('Fashione EAN 04-02-26.csv', dtype=str)
fe['Offer SKU'] = fe['PLU']
fe = pd.merge(fe, style, on='Style', how='left')
fe = fe[['Offer SKU', 'Style', 'Colour', 'Size', 'Category']]
fe['Category'] = fe['Category'].fillna('OTHER')
fe.head()

    Offer SKU Style      Colour Size Category
0  0002875800   007    BLK/BLUE    S   GLOVES
1  0002875801   007    BLK/BLUE    M   GLOVES
2  0002875802   007    BLK/BLUE    L   GLOVES
3  0002875803   007    BLK/BLUE   XL   GLOVES
4  0002876200   007  BLK/PURPLE    S   GLOVES

In [24]:
df = df[['Offer SKU', 'Type', 'Quantity', 'Amount']]
df = pd.merge(df, fe, on='Offer SKU', how='left')

In [25]:
df

,Offer SKU,Type,Quantity,Amount,Style,Colour,Size,Category
0,0004934200,Order amount,1,35.54,63753,MANDARIN,ONE SIZE,HANDBAGS
1,0004934200,Shipping charges,1,0.00,63753,MANDARIN,ONE SIZE,HANDBAGS
2,0004934200,Commission,1,-7.11,63753,MANDARIN,ONE SIZE,HANDBAGS
3,0004934200,Commission tax,1,-1.42,63753,MANDARIN,ONE SIZE,HANDBAGS
4,0004934400,Order amount,1,35.54,63753,parafin,ONE SIZE,HANDBAGS
...,...,...,...,...,...,...,...,...
494105,0004930900,Commission tax,1,-2.20,64198,2 tone tan,ONE SIZE,HANDBAGS
494106,0005433500,Order amount,1,37.99,oxford,BLACK,ONE SIZE,HANDBAGS
494107,0005433500,Shipping charges,1,0.00,oxford,BLACK,ONE SIZE,HANDBAGS
494108,0005433500,Commission,1,-7.60,oxford,BLACK,ONE SIZE,HANDBAGS
494109,0005433500,Commission tax,1,-1.52,oxford,BLACK,ONE SIZE,HANDBAGS

Type
Order amount              107463
Shipping charges          107463
Commission                107463
Commission tax            107463
Order amount refund        15656
Shipping charge refund     15656
Commission refund          15656
Commission tax refund      15656
Manual invoice               768
Manual invoice tax           768
Payment                       40
Subscription fee              24
Subscription tax              24
Manual credit                  5
Manual credit tax              5
Name: count, dtype: int64